- hosts: localhost
  name: Create NFS SVM
  gather_facts: false
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname: "10.128.16.23"
      username: "admin"
      password: "netapp13!"
      https: true
      validate_certs: false
      use_rest: true

  tasks:
  - name: Creating the SVM
    netapp.ontap.na_ontap_svm:
      state: "present"
      name: testsvm
      allowed_protocols: "nfs"